//@version=3
study("4 JMA", overlay=true)

// A simple crossover strategy with 4 Jurik's moving average lines UPDATE

jmax(src, len, p) =>
    beta = 0.45*(len-1)/(0.45*(len-1)+2)
    alpha = pow(beta, p)
    L0=0.0, L1=0.0, L2=0.0, L3=0.0, L4=0.0
    L0 := (1-alpha)*src + alpha*nz(L0[1])
    L1 := (src - L0[0])*(1-beta) + beta*nz(L1[1])
    L2 := L0[0] + L1[0]
    L3 := (L2[0] - nz(L4[1]))*((1-alpha)*(1-alpha)) + (alpha*alpha)*nz(L3[1])
    L4 := nz(L4[1]) + L3[0]
	L4
	
source = input(close)
len1 = input(18, minval=1)
len2 = input(16, minval=1)
len3 = input(14, minval=1)
crosslen = input(2, minval=1)
pow = input(3)

ma1 = jmax(source, len1, pow)
ma2 = jmax(source, len2, pow)
ma3 = jmax(source, len3, pow)
mabase = jmax(source, 20, pow)
macross = jmax(source, crosslen, pow)

plot(ma1, color=blue)
plot(ma2, color=teal)
plot(ma3, color=navy)
plot(mabase, color=orange, linewidth=2)

longCondition = crossover(macross, mabase)
shortCondition = crossunder(macross, mabase)

plot(longCondition? ma3:na, style=circles, color=lime, linewidth=8)
plot(shortCondition? ma3:na, style=circles, color=fuchsia, linewidth=8)

// longCondition = crossover(ma3, mabase)
// if (longCondition)
//     strategy.entry("4maLE", strategy.long)

// shortCondition = crossunder(ma3, mabase)
// if (shortCondition)
//     strategy.entry("4maSE", strategy.short)
    
