//@version=3
study("Mean Reversion and Momentum - Indicator version", "MRM", false)

// Mean Reversion and Momentum
// Interpretation:
// - Divergence means trend reversal
// - Parallel movement means trend continuation
// Squares above serve as a confirming signal

average(src, len) => sum(src, len) / len

mmax(x,y) =>
    m = 0.0
    for i=1 to y
        if x[i] > m
            m := x[i]
    m
    
mmin(x,y) =>
    m = 0.0
    for i=1 to y
        if x[i] < m
            m := x[i]
    m

scale(data, num) => (data - mmin(data, num)) / (mmax(data, num) - mmin(data, num)) 

src = input(close)

mean_period_short=input(2) //5
mean_period_long=input(8)  //20
buy_threshold=input(1., step=0.01)
sell_threshold=input(1., step=0.01)

mean_short = average(src, mean_period_short)
mean_long = average(src, mean_period_long)
beta = mean_short / mean_long

//plot(hlc3 > mean_long and beta > buy_threshold ? 1 : hlc3 < mean_short and beta < sell_threshold ? 0 : 0.5, style=line, color=gray, transp=0)
plotshape(hlc3 > mean_long and beta > buy_threshold, location=location.top, style=shape.square, color=green, transp=70)
plotshape(hlc3 < mean_short and beta < sell_threshold, location=location.top, style=shape.square,  color=red, transp=70)


len = input(20, minval=2)
tframe = input(2, minval=1)
use_rev = input(false)

calculate_return(src, len, tf) =>
    mean = 0.0, sd = 0.0, log_return = 0.0, mom = 0.0, reversal = 0.0
    //calculate the mean for further use
    mean := average(src, len)
    //calculate the standard deviation
    sd := stdev(src, len)
    // take the return as depend variable
    log_return := src - src[tf*1]
    // calculate the reversal factor
    reversal := (src[tf*1] - mean)/sd
    // calculate the momentum factor
    mom := src[1] - src[tf*4]
    [mean, sd, log_return, reversal, mom]

[mean, sd, log_return, reversal, mom] = calculate_return(src, len, tframe)

plot(use_rev?scale(reversal,200):na, linewidth=2, color=maroon, transp=50)
plot(scale(log_return,300), linewidth=2, color=green, transp=0)
plot(scale(mom,300), linewidth=2, color=red, transp=0)
//plot(scale(sd,300), linewidth=2, color=silver)
