//@version=3
study("Squeeze Momentum Indicator (v.3)", "SQZMOM_mod3", false)

// Squeeze Momentum Indicator mod#3 [LazyBear, KıvanÇ fr3762, Capissimo]

// This is a corrected version of Squeeze Indicator that initially was authored by LazyBear 
// and modified by KıvanÇ @fr3762 (twitter)
// Indicator description: http://www.forextrading-pips.com/squeeze-indicator/
// List of all my indicators: https://www.tradingview.com/u/capissimo/#published-scripts

src = input(close, title="Data source")
// This parameter originally was 20. Can be anything below that. 
// The less, the more sensitive the indicator.
// To be optimized
length   = input(10, title="BB Length")  
// This parameter must be equal to the length param above.
// If not, the indicator will show gaps in the squeeze signals
lengthKC = input(10, title="KC Length")   

mult   = input(2.0, step=0.1, title="BB MultFactor")  // standard
multKC = input(1.3, step=0.1, title="KC MultFactor")  // originally it was 1.5
siglen = input(5, title="Signal Length")
use_tr = input(true, title="Use TrueRange (KC)", type=bool)

NumDevsUp = 2, NumDevsDn = -2   // UPDATE !

// Calculate BB
basis = sma(src, length)
dev   = stdev(src, length)         // UPDATE !
upperBB = basis + NumDevsUp * dev  // UPDATE !
lowerBB = basis + NumDevsDn * dev  // UPDATE !

// Calculate KC
ma = sma(src, lengthKC)
range   = use_tr ? tr : (high - low)
rangema = sma(range, lengthKC)
upperKC = ma + rangema * multKC
lowerKC = ma - rangema * multKC

// When both the upper and lower Bollinger Bands go inside the Keltner Channel, the squeeze is on.
// When the Bollinger Bands (BOTH lines) start to come out of the Keltner Channel, the squeeze has been released (off). 
// When one of the Bollinger Bands is out of Keltner Channel, no highlighting is done.
sqzOn  = (lowerBB > lowerKC) and (upperBB < upperKC) 
sqzOff = (lowerBB <= lowerKC) and (upperBB >= upperKC)  // UPDATE from < and >
noSqz  = (sqzOn == false) and (sqzOff == false)

val = linreg(src - avg(avg(highest(high, lengthKC), lowest(low, lengthKC)), sma(close,lengthKC)), lengthKC,0)
sig = sma(val, siglen) 

bcolor = val > 0, 
            iff( val > nz(val[1]), lime, green),
            iff( val < nz(val[1]), red, maroon)
scolor = noSqz ? na : sqzOn ? black : silver 

plot(val, color=blue, linewidth=2)
plot(sig, color=red, linewidth=2)
plot(0, color=scolor, style=circles, linewidth=2, transp=0)
