//@version=4
study("Forecasting: Locally Weighted Regression (rescaled)", '', true)

// author: capissimo

// UPDATE: the original version works only with BTC. Here's a general version with rescaling.

//*** Functions
scaleMinimax(X, p, min, max) => 
    hi = highest(X, p), lo = lowest(X, p)
    (max - min) * (X - lo)/(hi - lo) + min

scale(X, p) => scaleMinimax(X, p, lowest(close, p), highest(close, p))

locally_weighted(x, p, b, mx) =>
    PI  = 3.14159265359
    l = 0.0
    for i=0 to p-1
        l := b + b*i + b*2*x[i] + b*sin(2*PI*i) + b*cos(2*PI*i)
    scale(linreg(l, p, 0), mx)

//*** Inputs 
price = input(close, "Price Data")
p     = input(5,     "Lookback Window")
span  = input(8,     "Rising/Falling span", minval=2)
crvs  = input(false, "Show curves?")
lbls  = input(true,  "Show Labels?")
mmx   = input(20,     "Scaler Lookback", minval=1)

//*** Main
BETA  = .5
lwr   = locally_weighted(price, p, BETA, mmx)	
lnr   = linreg(price, p, 0)
long  = crossunder(lwr, lnr) and falling(lwr, span) 
short = crossover(lwr, lnr) and rising(lwr, span) 

plot(crvs ? lwr : na, color=color.red, transp=0)
plot(crvs ? lnr : na, color=color.lime, transp=0)
plotshape(lbls and long  ? low  : na, location=location.belowbar, style=shape.labelup, color=color.lime, size=size.small, text=" ", textcolor=color.white, transp=0, offset=-1)
plotshape(lbls and short ? high : na, location=location.abovebar, style=shape.labeldown, color=color.red, size=size.small, text=" ", textcolor=color.white, transp=0, offset=-1)

alertcondition(long,  title='Buy',  message='go long')
alertcondition(short, title='Sell', message='go short') 
